---
permalink: sm-storage/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: Se refleja un volumen en forma síncrona a fin de replicar los datos en tiempo real entre las cabinas de almacenamiento para que la información quede protegida de los fallos del sitio y del sistema. Para ello, se seleccionan el volumen primario y el secundario que se desean usar en la relación de mirroring síncrono entre una cabina de almacenamiento local y una remota. 
---
= Crear un volumen reflejado síncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se refleja un volumen en forma síncrona a fin de replicar los datos en tiempo real entre las cabinas de almacenamiento para que la información quede protegida de los fallos del sitio y del sistema. Para ello, se seleccionan el volumen primario y el secundario que se desean usar en la relación de mirroring síncrono entre una cabina de almacenamiento local y una remota.

.Antes de empezar
* Debido a que la función Asynchronous Mirroring requiere la gestión de varias cabinas de almacenamiento, es necesario tener instalado SANtricity Unified Manager basado en explorador y haber detectado las dos cabinas de almacenamiento entre las cuales se desean reflejar datos. A continuación, desde Unified Manager, debe seleccionar la cabina de almacenamiento del volumen primario y hacer clic en *Iniciar* para abrir la instancia de SANtricity System Manager basada en explorador.
* Debe tener dos cabinas de almacenamiento.
* Cada cabina de almacenamiento debe tener dos controladoras.
* Las cabinas de almacenamiento de los volúmenes primario y secundario pueden ejecutar versiones de sistemas operativos diferentes. La versión mínima admitida es 7.84.
* Debe conocer la contraseña de las cabinas de almacenamiento remota y local.
* Las cabinas de almacenamiento local y remota deben estar conectadas a través de una estructura Fibre Channel.
* Debe haber seleccionado el volumen primario y el secundario que desea usar en la relación de reflejo síncrono.


.Acerca de esta tarea
El proceso de reflejar un volumen de manera síncrona es un procedimiento de varios pasos:

* <<Paso 1: Seleccione el volumen primario>>
* <<Paso 2: Seleccione el volumen secundario>>
* <<Paso 3: Seleccione la configuración de sincronización>>


Un volumen puede participar solo en una relación de reflejo.



== Paso 1: Seleccione el volumen primario

[role="lead"]
Debe seleccionar el volumen primario que desea usar en la relación de reflejo síncrono. Este volumen tiene el rol primario en la relación de reflejo.

.Antes de empezar
* Debe haber creado el volumen primario que desea usar en la relación de reflejo síncrono.
* El volumen primario deber ser un volumen estándar. No puede ser un volumen fino ni un volumen Snapshot.


.Pasos
. Debe realizar una de las siguientes acciones para acceder a la secuencia de mirroring síncrono:
+
** Seleccione MENU:almacenamiento[Mirroring síncrono > Mirror volume].
** Seleccione menu:Storage[Volumes > Copy Services > Mirror a volume sincrónicamente]. Aparecerá el cuadro de diálogo *Crear pareja reflejada síncrona*.


. Seleccione el volumen existente que desea usar como volumen primario del reflejo.
+
[NOTE]
====
Si se seleccionó un volumen en el icono volúmenes y es apto para reflejarlo, se seleccionará en forma predeterminada.

====
. Seleccione *Siguiente* y vaya a. <<Paso 2: Seleccione el volumen secundario>>.




== Paso 2: Seleccione el volumen secundario

[role="lead"]
Debe seleccionar el volumen secundario que desea usar en la relación de reflejo. Este volumen tendrá el rol secundario en la relación de reflejo.

.Antes de empezar
* Debe haber creado el volumen secundario que desea usar en la relación de reflejo síncrono.
* El volumen secundario deber ser un volumen estándar. No puede ser un volumen fino ni un volumen Snapshot.
* El volumen secundario deber tener al menos el tamaño del volumen primario.


.Acerca de esta tarea
Si selecciona un volumen secundario en la cabina de almacenamiento remota, el sistema muestra una lista de todos los volúmenes aptos para esa pareja reflejada. Si algún volumen no es apto para el uso, no se muestra en esa lista.

Los volúmenes que aparecen en este cuadro de dialogo se ordenan por capacidad, desde el volumen más cercano a la capacidad del volumen primario. Los volúmenes con una capacidad idéntica se ordenan en forma alfabética.

.Pasos
. Seleccione la cabina de almacenamiento remota en la que desea establecer una relación de reflejo con la cabina de almacenamiento local.
+
[NOTE]
====
Si la cabina de almacenamiento remota está protegida con contraseña, el sistema solicita la contraseña.

====
+
** Las cabinas de almacenamiento se enumeran en una lista por nombre. Si no asignó ningún nombre a una cabina de almacenamiento, esta se muestra en la lista como "unnamed".
** Si la cabina de almacenamiento que desea usar no está en la lista, añádala con Enterprise Management Window (EMW) de SANtricity Storage Manager. Seleccione MENU:Edit[Add Storage Array].


. Seleccione el volumen existente que desea usar como volumen secundario del reflejo.
+
[NOTE]
====
Si se eligió un volumen secundario con una capacidad mayor a la del volumen primario, la capacidad utilizable se restringe al tamaño del volumen primario.

====
. Haga clic en *Siguiente* y vaya a. <<Paso 3: Seleccione la configuración de sincronización>>.




== Paso 3: Seleccione la configuración de sincronización

[role="lead"]
Debe configurar la prioridad que tendrá en cuenta el propietario de la controladora del volumen primario para volver a sincronizar los datos con el volumen secundario después de una interrupción de la comunicación. Además, es necesario seleccionar la política de resincronización: Manual o automática.

.Pasos
. Use la barra de desplazamiento para configurar la prioridad de sincronización.
+
La prioridad de sincronización determina cuántos recursos del sistema se usan para completar la sincronización inicial y la operación de resincronización después de una interrupción de la comunicación en comparación con las solicitudes de I/o del servicio.

+
La prioridad que se configure en este cuadro de diálogo se aplicará tanto al volumen primario, como al secundario. Si después desea modificar la tasa del volumen primario, seleccione MENU:almacenamiento[Mirroring síncrono > más > Editar configuración].

+
.Más información acerca de las tasas de sincronización
[%collapsible]
====
Las tasas de prioridad de sincronización son las siguientes cinco:

** El más bajo
** Bajo
** Mediano
** Alto
** Máxima si la prioridad de sincronización se configuró con la tasa mínima, se prioriza la actividad de I/o y la operación de resincronización lleva más tiempo. Si la prioridad de sincronización se configuró con la tasa máxima, la operación de resincronización tiene prioridad, pero podría afectar a la actividad de I/o de la cabina de almacenamiento.


====
. Elija si desea volver a sincronizar las parejas reflejadas de la cabina de almacenamiento remota en forma manual o automática.
+
** *Manual* (la opción recomendada) -- Seleccione esta opción para requerir que la sincronización se reanude manualmente después de restaurar la comunicación a una pareja reflejada. Esta opción proporciona la mejor oportunidad para recuperar datos.
** *Automático* -- Seleccione esta opción para iniciar la resincronización automáticamente después de restaurar la comunicación a un par reflejado. Para reanudar manualmente la sincronización, vaya al menú:almacenamiento[Mirroring síncrono], resalte la pareja reflejada en la tabla y seleccione *Reanudar* en *más*.


. Haga clic en *Finalizar* para completar la secuencia de duplicación sincrónica.


.Resultados
System Manager realiza lo siguiente:

* Activa la función Synchronous Mirroring.
* Comienza la sincronización inicial entre la cabina de almacenamiento local y la remota.
* Configura la prioridad de sincronización y la política de resincronización.


.Después de terminar
Seleccione MENU:Inicio[Ver operaciones en curso] para ver el progreso de la operación de mirroring síncrono. Es posible que esta operación demore y que afecte el rendimiento del sistema.
