---
permalink: sm-storage/what-is-segment-sizing.html 
sidebar: sidebar 
keywords: segment size 
summary: 'Un segmento es la cantidad de datos en kilobytes (KiB) que se almacenan en una unidad antes de que la cabina de almacenamiento pase a la unidad siguiente en la franja (grupo RAID). El tamaño de segmento aplica solo a grupos de volúmenes, no a pools.' 
---
= ¿Qué es el tamaño de segmento?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un segmento es la cantidad de datos en kilobytes (KiB) que se almacenan en una unidad antes de que la cabina de almacenamiento pase a la unidad siguiente en la franja (grupo RAID). El tamaño de segmento aplica solo a grupos de volúmenes, no a pools.

El tamaño de los segmentos está definido por la cantidad de bloques de datos que contiene. Por ejemplo:

* Segmento de 64 KiB = 128 bloques de datos
* Segmento de 512 KiB = 1024 bloques de datos


Para determinar el tamaño de segmento, se debe conocer el tipo de datos que se almacenará en un volumen. Si una aplicación utiliza habitualmente escrituras y lecturas aleatorias pequeñas (IOPS), por lo general, funcionará mejor un tamaño de segmento más pequeño. Por el contrario, si la aplicación realiza escrituras y lecturas secuenciales grandes (rendimiento), por lo general, funcionará mejor un tamaño de segmento grande.

Independientemente de si una aplicación utiliza escrituras y lecturas aleatorias pequeñas o escrituras y lecturas secuenciales grandes, la cabina de almacenamiento rendirá mejor si el tamaño del segmento es mayor al tamaño típico del fragmento de bloque de datos. Habitualmente, esto facilita y agiliza el acceso de las unidades a los datos, lo cual resulta importante para un mejor rendimiento de la cabina de almacenamiento.



== En un entorno en el cual el rendimiento de IOPS es importante

En un entorno de operaciones de I/o por segundo (IOPS), la cabina de almacenamiento tiene un mejor rendimiento si se utiliza un tamaño de segmento mayor al tamaño típico del bloque de datos ("fragmento"") que se lee/escribe en una unidad. Esto garantiza que cada fragmento se escriba en una unidad única.



== En un entorno en el cual el rendimiento es importante

En un entorno de rendimiento, el tamaño del segmento debe ser una fracción entera de las unidades totales para los datos y del tamaño de fragmento de datos típico (tamaño de I/o). Esto permite la distribución de los datos como una franja única en las unidades del grupo de volúmenes, lo que lleva a lecturas y escrituras más rápidas.

Por ejemplo, en un grupo de volúmenes RAID 5 de 5 unidades (4+1), si el tamaño típico de "'fragmento'" de lectura/escritura es 2 MIB, un tamaño de segmento de 512 KiB (una fracción par [1/4] del tamaño total del fragmento) sería la mejor opción para el tamaño de segmento de volumen de la aplicación porque se garantiza que cada lectura/escritura se escriba como una franja única de las unidades del grupo de volúmenes.
