---
permalink: sm-settings/configure-iscsi-ports-hardware.html 
sidebar: sidebar 
keywords: configure, iscsi, ports 
summary: Si la controladora incluye una conexión de host iSCSI, los ajustes del puerto iSCSI se pueden configurar desde la página hardware o la página sistema. 
---
= Configure los puertos iSCSI
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la controladora incluye una conexión de host iSCSI, los ajustes del puerto iSCSI se pueden configurar desde la página hardware o la página sistema.

.Antes de empezar
* La controladora debe incluir puertos iSCSI; de lo contrario, la configuración de iSCSI no estará disponible.
* Se debe conocer la velocidad de la red (la tasa de transferencia de datos entre los puertos y el host).


.Acerca de esta tarea
En esta tarea, se describe cómo acceder a la configuración del puerto iSCSI desde la página hardware. También puede acceder a la configuración desde la página sistema (menú:Configuración[sistema]).

[NOTE]
====
La configuración y las funciones iSCSI solamente aparecen si la cabina de almacenamiento es compatible con iSCSI.

====
.Pasos
. Seleccione *hardware*.
. Si el gráfico muestra las unidades, haga clic en *Mostrar parte posterior de la bandeja*.
+
El gráfico cambia y muestra las controladoras en lugar de las unidades.

. Haga clic en la controladora con los puertos iSCSI que desea configurar.
+
Aparece el menú contextual de la controladora.

. Seleccione *Configurar puertos iSCSI*.
+
[NOTE]
====
La opción *Configurar puertos iSCSI* aparece sólo si System Manager detecta puertos iSCSI en la controladora.

====
+
Se abre el cuadro de diálogo Configurar puertos iSCSI.

. En la lista desplegable, seleccione el puerto que desea configurar y, a continuación, haga clic en *Siguiente*.
. Seleccione los valores del puerto de configuración y, a continuación, haga clic en *Siguiente*.
+
Para ver todas las opciones de configuración de puertos, haga clic en el enlace Mostrar más opciones de puerto que se encuentra a la derecha del cuadro de diálogo.

+
.Detalles del campo
[%collapsible]
====
|===
| Opción de configuración de puertos | Descripción 


 a| 
Habilite IPv4/Habilitar IPv6
 a| 
Seleccione una o ambas opciones para habilitar la compatibilidad con las redes IPv4 e IPv6. NOTA: Si desea desactivar el acceso al puerto, anule la selección de las dos casillas de verificación.



 a| 
Puerto de escucha TCP (disponible cuando se hace clic en Mostrar más opciones de puerto)
 a| 
De ser necesario, introduzca un nuevo número de puerto.

El puerto de escucha es el número de puerto TCP que la controladora utiliza para escuchar inicios de sesión iSCSI de iniciadores iSCSI del host. El puerto de escucha predeterminado es 3260. Debe introducir 3260 o un valor entre 49 49152 y 65 65535.



 a| 
Tamaño de MTU (disponible cuando se hace clic en Mostrar más opciones de puerto)
 a| 
De ser necesario, introduzca un nuevo tamaño en bytes para la unidad de transmisión máxima (MTU).

El tamaño de MTU predeterminado es de 1500 bytes por trama. Debe introducir un valor entre 1500 y 9000.



 a| 
Habilite las respuestas PING de ICMP PING
 a| 
Seleccione esta opción para habilitar el protocolo de mensajes de control de Internet (ICMP). Los sistemas operativos de equipos en red usan ese protocolo para enviar mensajes. Esos mensajes ICMP determinan si es posible acceder a un host y cuánto tiempo debe transcurrir para enviar y recibir los paquetes de ese host.

|===
====
+
Si seleccionó Habilitar IPv4, se abre un cuadro de diálogo para seleccionar la configuración de IPv4 después de hacer clic en Siguiente. Si seleccionó Habilitar IPv6, se abre un cuadro de diálogo para seleccionar la configuración de IPv6 después de hacer clic en Siguiente. Si seleccionó ambas opciones, se abre primero el cuadro de diálogo de configuración de IPv4, y después de hacer clic en Siguiente, se abre el cuadro de diálogo de configuración de IPv6.

. Configure los valores para IPv4 o IPv6 de forma automática o manual. Para ver todas las opciones de configuración de puertos, haga clic en el enlace *Mostrar más valores* situado a la derecha del cuadro de diálogo.
+
.Detalles del campo
[%collapsible]
====
|===
| Opción de configuración de puertos | Descripción 


 a| 
Obtener configuración automáticamente
 a| 
Seleccione esta opción para obtener automáticamente la configuración.



 a| 
Especificar manualmente la configuración estática
 a| 
Seleccione esta opción e introduzca una dirección estática en los campos. (Si lo desea, puede cortar y pegar direcciones en los campos.) En el caso de IPv4, incluya la máscara de subred y la puerta de enlace. En el caso de IPv6, incluya la dirección IP enrutable y la dirección IP del enrutador.



 a| 
Habilite la compatibilidad con VLAN (disponible cuando se hace clic en Mostrar más opciones)
 a| 
Seleccione esta opción para habilitar una VLAN e introducir su ID. Una red de área local virtual (VLAN) es una red lógica que se comporta como si estuviese físicamente separada de otras redes de área local virtuales y físicas (LAN) admitidas por los mismos switches, los mismos enrutadores, o ambos.



 a| 
Habilite la prioridad de ethernet (disponible cuando haga clic en Mostrar más opciones)
 a| 
Seleccione esta opción para habilitar el parámetro que determina la prioridad de acceso a la red. Use la barra deslizante para seleccionar una prioridad entre 1 (más baja) y 7 (más alta).

En un entorno de red de área local (LAN) compartida, como Ethernet, es posible que muchas estaciones compitan por el acceso a la red. El acceso se otorga por orden de llegada. Es posible que dos estaciones intenten acceder a la red al mismo tiempo, lo que provoca que ambas estaciones se apagen y esperen antes de volver a intentarlo. Este proceso se minimiza para Ethernet con switch, donde existe una sola estación conectada a un puerto del switch.

|===
====
. Haga clic en *Finalizar*.

