---
permalink: sm-settings/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: 'Si la controladora incluye una conexión para NVMe over roce (RDMA over Converged Ethernet), es posible configurar las opciones del puerto NVMe desde la página hardware o la página sistema.' 
---
= Configure los puertos NVMe over roce
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la controladora incluye una conexión para NVMe over roce (RDMA over Converged Ethernet), es posible configurar las opciones del puerto NVMe desde la página hardware o la página sistema.

.Antes de empezar
* La controladora debe incluir un puerto de host NVMe over roce; de lo contrario, los ajustes de NVMe over roce no estarán disponibles en System Manager.
* Se debe conocer la dirección IP de la conexión de host.


.Acerca de esta tarea
Es posible acceder a la configuración de NVMe over roce desde la página *hardware* o desde el menú:Configuración[sistema]. En esta tarea, se describe cómo configurar los puertos desde la página hardware.

[NOTE]
====
La configuración y las funciones de NVMe over roce aparecen solamente si la controladora de la cabina de almacenamiento contiene un puerto NVMe over roce.

====
.Pasos
. Seleccione *hardware*.
. Si el gráfico muestra las unidades, haga clic en *Mostrar parte posterior de la bandeja*.
+
El gráfico cambia y muestra las controladoras en lugar de las unidades.

. Haga clic en la controladora que tenga el puerto NVMe over roce que desea configurar.
+
Aparece el menú contextual de la controladora.

. Seleccione *Configurar puertos NVMe over roce*.
+
Se abre el cuadro de diálogo Configurar puertos NVMe over roce.

. En la lista desplegable, seleccione el puerto HIC que desea configurar.
. Haga clic en *Siguiente*.
+
Para ver todas las configuraciones de puerto, haga clic en el enlace *Mostrar más opciones de puerto* situado a la derecha del cuadro de diálogo.

+
.Detalles del campo
[%collapsible]
====
|===
| Opción de configuración de puertos | Descripción 


 a| 
Velocidad de puerto ethernet configurada
 a| 
Seleccione la velocidad que coincida que la capacidad de velocidad del SFP en el puerto.



 a| 
Habilite IPv4/Habilitar IPv6
 a| 
Seleccione una o ambas opciones para habilitar la compatibilidad con las redes IPv4 e IPv6.


NOTE: Si desea deshabilitar el acceso al puerto, cancele la selección de las dos casillas de comprobación.



 a| 
Tamaño de MTU (disponible cuando se hace clic en Mostrar más opciones de puerto)
 a| 
De ser necesario, introduzca un nuevo tamaño en bytes para la unidad de transmisión máxima (MTU).

El tamaño de MTU predeterminado es de 1500 bytes por trama. Debe introducir un valor entre 1500 y 9000.

|===
====
+
Si seleccionó Habilitar IPv4, se abre un cuadro de diálogo para seleccionar la configuración de IPv4 después de hacer clic en Siguiente. Si seleccionó Habilitar IPv6, se abre un cuadro de diálogo para seleccionar la configuración de IPv6 después de hacer clic en Siguiente. Si seleccionó ambas opciones, se abre primero el cuadro de diálogo de configuración de IPv4, y después de hacer clic en Siguiente, se abre el cuadro de diálogo de configuración de IPv6.

. Configure los valores para IPv4 o IPv6 de forma automática o manual.
+
.Detalles del campo
[%collapsible]
====
|===
| Opción de configuración de puertos | Descripción 


 a| 
Obtener configuración automáticamente
 a| 
Seleccione esta opción para obtener automáticamente la configuración.



 a| 
Especificar manualmente la configuración estática
 a| 
Seleccione esta opción e introduzca una dirección estática en los campos. (Si lo desea, puede cortar y pegar direcciones en los campos.) En el caso de IPv4, incluya la máscara de subred y la puerta de enlace. En el caso de IPv6, incluya la dirección IP enrutable y la dirección IP del enrutador.

|===
====
. Haga clic en *Finalizar*.

