---
permalink: sm-settings/delete-trusted-certificates.html 
sidebar: sidebar 
keywords: delete, trusted, certificates 
summary: Es posible eliminar cualquiera de los certificados importados por el usuario. 
---
= Elimine certificados de confianza
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar cualquiera de los certificados importados por el usuario.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.
* Si actualiza a una nueva versión de certificado de confianza, el certificado actualizado debe importarse antes de eliminar el anterior.


[CAUTION]
====
Es posible que pierda acceso al sistema si elimina un certificado utilizado para autenticar los certificados de gestión de la cabina de almacenamiento o el servidor LDAP antes de importar un certificado de reemplazo.

====
.Acerca de esta tarea
Esta tarea describe la manera de eliminar certificados importados por el usuario. Los certificados predefinidos no pueden eliminarse.

.Pasos
. Seleccione MENU:Settings[Certificates].
. Seleccione la ficha *Trusted*.
+
En la tabla, se muestran los certificados de confianza de la cabina de almacenamiento.

. En la tabla, seleccione el certificado que desea eliminar.
. Haga clic en menú:tareas no comunes[Eliminar].
+
Se abrirá el cuadro de diálogo Confirmar eliminación de certificado de confianza.

. Tipo `delete` En el campo y, a continuación, haga clic en *Eliminar*.

