---
permalink: sm-settings/enable-or-disable-legacy-management-interface.html 
sidebar: sidebar 
keywords: enable, disable, legacy, management, interface 
summary: 'Es posible habilitar o deshabilitar la interfaz de gestión heredada (Symbol), que es un método de comunicación entre la cabina de almacenamiento y el cliente de gestión. De manera predeterminada, la interfaz de gestión heredada está activada. Si se desactiva, la cabina de almacenamiento y su cliente de gestión utilizan un método más seguro de comunicación (API DE REST a través de https); sin embargo, ciertas herramientas y tareas pueden verse afectadas si se deshabilita la cabina.' 
---
= Habilitar o deshabilitar la interfaz de gestión heredada
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible habilitar o deshabilitar la interfaz de gestión heredada (Symbol), que es un método de comunicación entre la cabina de almacenamiento y el cliente de gestión. De manera predeterminada, la interfaz de gestión heredada está activada. Si se desactiva, la cabina de almacenamiento y su cliente de gestión utilizan un método más seguro de comunicación (API DE REST a través de https); sin embargo, ciertas herramientas y tareas pueden verse afectadas si se deshabilita la cabina.

.Acerca de esta tarea
La configuración afecta a las operaciones de la siguiente manera:

* *Activado* (predeterminado): Es la configuración necesaria para la duplicación, para los comandos de la CLI que funcionan sólo en las matrices de almacenamiento E5700 y E5600, y para otras herramientas como la utilidad QuickConnect y el adaptador OCI.
* *Off* -- Configuración requerida para reforzar la confidencialidad en las comunicaciones entre la matriz de almacenamiento y el cliente de administración, y para acceder a herramientas externas. Opción recomendada para configurar un servidor de directorio (LDAP).


.Pasos
. Seleccione MENU:Settings[System].
. Desplácese hacia abajo hasta *Configuración adicional* y, a continuación, haga clic en *Cambiar interfaz de administración*.
. En el cuadro de diálogo, haga clic en *Sí* para continuar.

