---
permalink: sm-settings/how-do-i-know-what-certificates-need-to-be-uploaded-to-system-manager.html 
sidebar: sidebar 
keywords: how, what, know, certificates, need, uploaded, system manager 
summary: Para la gestión de claves externas, debe importar dos tipos de certificados para la autenticación entre la cabina de almacenamiento y el servidor de gestión de claves, de forma tal que exista confianza mutua entre las dos entidades. 
---
= ¿Cómo saber qué certificados deben cargarse en System Manager?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la gestión de claves externas, debe importar dos tipos de certificados para la autenticación entre la cabina de almacenamiento y el servidor de gestión de claves, de forma tal que exista confianza mutua entre las dos entidades.

Un certificado de cliente valida las controladoras de la cabina de almacenamiento para que el servidor de gestión de claves pueda confiar en sus direcciones IP. Para obtener un certificado de cliente, debe completar una CSR para la cabina de almacenamiento y luego cargarlo al servidor de gestión de claves. Desde el servidor, genere un certificado de cliente y luego use System Manager para importarlo.

Un certificado de servidor de gestión de claves valida el servidor de gestión de claves para que la cabina de almacenamiento pueda confiar en su dirección IP. Para obtener un certificado de servidor de gestión de claves, debe generarlo en el servidor de gestión de claves.
