---
permalink: sm-settings/import-trusted-certificates-for-controllers-acting-as-client.html 
sidebar: sidebar 
keywords: import, trusted, certificates, controllers 
summary: 'Después de recibir certificados digitales de una entidad de certificación (CA), puede importar la cadena de certificados (intermedio y raíz) para las controladoras.' 
---
= Importe certificados de confianza para las controladoras
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de recibir certificados digitales de una entidad de certificación (CA), puede importar la cadena de certificados (intermedio y raíz) para las controladoras.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.
* Generó una solicitud de firma de certificación (archivo .CSR) y la envió a la CA.
* La CA devolvió archivos de certificado de confianza.
* Los archivos de certificado están instalados en el sistema local.


.Acerca de esta tarea
En esta tarea, se describe cómo cargar los certificados de confianza para las controladoras de la cabina de almacenamiento.

.Pasos
. Seleccione MENU:Settings[Certificates].
. En la ficha *Trusted*, seleccione *Importar*.
+
Se abre un cuadro de diálogo para importar los archivos de certificado de confianza.

. Haga clic en *examinar* para seleccionar los archivos de certificado para los controladores.
+
Se muestran los nombres de los archivos en el cuadro de diálogo.

. Haga clic en *Importar*.


.Resultados
Los archivos se cargan y validan.

.Después de terminar
Importe el certificado de gestión.
