---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: view, imported, certificate, information 
summary: Desde la página certificados, es posible ver el tipo de certificado, la entidad de certificación y el rango válido de fechas de certificados importados anteriormente. 
---
= Vea información de certificaciones importadas
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desde la página certificados, es posible ver el tipo de certificado, la entidad de certificación y el rango válido de fechas de certificados importados anteriormente.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.


.Acerca de esta tarea
En esta tarea, se describe cómo ver información de certificados instalados por el usuario o instalados previamente.

.Pasos
. Seleccione MENU:Settings[Certificates].
. Seleccione una de las pestañas para ver información sobre certificados de gestión de controladoras, certificados de confianza y certificados de un servidor de gestión de claves.
+
[cols="25h,~"]
|===
| Pestaña | Descripción 


 a| 
Gestión de cabinas
 a| 
Permite ver información sobre todos los certificados de servidor importados de las controladoras.



 a| 
De confianza
 a| 
Permite ver información sobre todos los certificados de confianza (raíz) importados de las controladoras. Utilice el campo de filtro en *Mostrar certificados...* para ver certificados instalados por el usuario o instalados previamente.

** *Instalado por el usuario*. Los certificados que un usuario cargó en la cabina de almacenamiento (incluyen certificados de confianza, certificados LDAPS y certificados de la Federación de identidades).
** *Preinstalado*. Certificados incluidos en la cabina de almacenamiento.




 a| 
Gestión de claves
 a| 
Permite ver información sobre todos los certificados de gestión (firmados) importados para un servidor de gestión de claves externo.

|===

