---
permalink: sm-support/view-nvme-over-infiniband-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, infiniband, statistics, packages 
summary: Es posible ver datos acerca de las conexiones NVMe over InfiniBand a la cabina de almacenamiento. 
---
= Vea paquetes de estadísticas de NVMe over InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ver datos acerca de las conexiones NVMe over InfiniBand a la cabina de almacenamiento.

.Acerca de esta tarea
En System Manager, se muestran los siguientes tipos de estadísticas de NVMe over InfiniBand. Todas las estadísticas son de solo lectura y no pueden configurarse.

* *Estadísticas de la controladora NVMe* -- se muestran estadísticas de la controladora NVMe, que incluyen tiempos de espera y fallos de conexión.
* *Estadísticas de la cola de NVMe* -- proporciona estadísticas para la cola de NVMe, incluidas solicitudes de conexión y estado de comandos.


Es posible ver cada una de las estadísticas como estadísticas sin configurar o estadísticas de base. Las estadísticas sin configurar son todas las estadísticas recogidas desde que se iniciaron las controladoras. Las estadísticas de base son las estadísticas de un momento específico que se recogen desde el establecimiento de la hora de la línea de base.

Es posible acceder a estadísticas de NVMe over InfiniBand desde las páginas sistema (MENU:Settings[System]) o Soporte. Estas instrucciones describen cómo acceder a las estadísticas desde la página Soporte.

.Pasos
. Seleccione menú:ficha Soporte[Centro de soporte > Diagnóstico].
. Seleccione *Ver paquetes de estadísticas de NVMe over InfiniBand*.
. Para establecer la línea de base, haga clic en *establecer nueva línea de base*.
+
La configuración de la línea de base establece un nuevo punto de partida para la recogida de estadísticas. Se usa la misma línea de base para todas las estadísticas de NVMe.


